### PR TITLE
Added pipes graphic to 'for' documentation

### PR DESCRIPTION
**Pull request by mitchellwrosen**
I found the pipes graphics from `Pipes.Tutorial` really helpful. Do you think it would be overkill to add them to the documentation for pipes combinators as well? This patch includes just one example but I'll gladly make the rest if you think it's a good idea.

### CODE REVIEW

**Comment by Gabriel439** [comment]
Yeah, definitely!  Only one minor nitpick: could you connect the `b` and `b'` in the first two like the examples from `Pipes.Core` (such as [this one](http://hackage.haskell.org/package/pipes-4.1.5/docs/Pipes-Core.html#g:3))?

**Comment by mitchellwrosen** [comment]
Oh yeah! I forgot about those. How about the "simplified" functions ('for' vs. (//>)) are coupled with simplified diagrams, and a hyperlink to the more general one? I've updated the PR to show you what I mean.

**Comment by Gabriel439** [comment]
That sounds like a good idea.  The only thing I'd suggest is omitting the `x` from the simplified diagram for `for`.

**Comment by mitchellwrosen** [comment]
Even though it's part of the downstream flow? Just above the diagram are aliases to 'for' which include `Pipe x b m r -> (b -> Pipe x c m ()) -> Pipe x c m r` and others.

**Comment by Gabriel439** [comment]
Never mind.  Keep it the way it is.  I realized that you were aiming for the most general unidirectional version.

**Pull request merged**
