### PR TITLE
Add support for ExceptT in Pipes.Lift

### PR DESCRIPTION
**Pull request by k0001**
This depends on the version of `mmorph` that is in GitHub which provides instances for `ExceptT`.

There is no `liftCatchExcept` as it would be exactly the same as `liftCatchError`. `catchExcept` is a bit more general than its `catchError` counterpart in that it the error type can change.

There's no urgency to merge this from my side, I just had some spare minutes and decided to add this and send a pull request.

### CODE REVIEW

**Comment by treeowl** [comment]
It looks like this has been done in some other commit. Can this PR be closed?

**Comment by Gabriel439** [comment]
@treeowl: Yeah, I'll go ahead and close this.  Also, I'll go ahead and add you as a contributor so you can be proactive in fixing anything out of place

**Comment by treeowl** [comment]
Thanks!

**Comment by Gabriel439** [comment]
@treeowl: You're welcome! 🙂

**Pull request closed without merging**
